### PR TITLE
Add the Vixi project to the list of frontends

### PR DESCRIPTION
**Pull request by Peltoche**
Hi!
Everything is in the title. I have just started a new side-project which consist into a  "Vim like" frontend from the xi-editor. I was hoping to add it to the frontend list inside the README.

### CODE REVIEW

**Comment by jansol** [comment]
Isn't there some other project with the same name and roughly the same goals already?

**Comment by Peltoche** [comment]
Damn! I never had the idea to check! This could be problematic.

There is [jakalope/vixi](https://github.com/jakalope/vixi) but it doesn't seems active.

**Comment by jansol** [comment]
Maybe you can join forces with @jakalope if they are still interested... Their code is MIT licensed so you could at least check if there's something you can reuse.

Anyway personally I don't have a strong opinion on which projects should be in the readme. If you can collaborate on this that'll just make everyone's lives easier IMHO.

**Comment by Cogitri** [comment]
https://github.com/xi-editor/xi-editor.github.io/blob/master/frontends.md should most likely be changed as well.

**Comment by Cogitri** [comment]
Sooo...what's the status on this?

**Comment by cmyr** [comment]
oops. I'm happy to merge.

**Comment by cmyr** [comment]
jakalope was there first but also hasn't been working on any of this stuff in ages, so let's prioritize the more active project.

**Pull request merged**
