### PR TITLE
explicitly describe as not ready for daily use

### PR DESCRIPTION
**Pull request by matkoniecz**
## Summary
Make more clear that while promising this project is not useful for people looking for a new editor - at this moment it is useful for people interested in developing a new editor

## Related Issues
related to #816

## Review Checklist

- [x] I have responded to reviews and made changes where appropriate (not yet applicabble).
- [x] I have tested the code with `cargo test --all` / `./rust/run_all_checks` (not applicable).
- [x] I have updated comments / documentation related to the changes I made (not applicable).
- [x] I have rebased my PR branch onto xi-editor/master (not yet applicable).

### CODE REVIEW

**Comment by jansol** [comment]
Thanks for the PR! Unfortunately I'm inclined to **close** this:

First off, this is the repo for xi-core which is not usable by itself to begin with, as is stated in the README multiple times already, starting from the very top of the file.

Additionally I use xi-mac as my primary code editor already, and I am fairly sure other developers have mentioned doing so as well so the suggested text as written is not strictly speaking true. It also comes of as quite self-deprecating and does not address the actual issue mentioned in the OP, namely the lack of downloadable binaries.

Speaking of xi-mac, the README in that repo actually does mention the lack of binaries as well as the plan for providing them in the future right at the beginning. Of course some people won't bother reading any of that and ask for binaries anyway. I don't think there is anything we can do about those.

**Comment by matkoniecz** [comment]
Feel free to close if that would be misleading.

So with `xi-core` and `xi-mac` combination is ready? Maybe https://github.com/xi-editor/xi-editor#frontends should have one more category "ready for daily use" to differentiate https://github.com/xi-editor/xi-mac and https://github.com/sw5cc/xi-qt that are currently in the same section what seems to not make sense.

**Comment by cmyr** [comment]
@matkoniecz I would be hesitant about 'ready for daily use', but xi-mac is certainly a useable, light-weight editor.

I appreciate the sentiment of this PR, but I agree with @jansol; I think it's clear enough right now that this is a work in progress. :)

**Comment by jansol** [comment]
I'm absolutely on board with a progress indicator for the various known frontends. The main problem is that someone would have to evaluate them all and keep the indicators up to date. It's also not entirely clear to me how progress should be measured. If you have ideas, let's hear them.

**Comment by matkoniecz** [comment]
I started writing abouit my idea but decided that it will be easier to propose it as a PR - see #1079

**Pull request closed without merging**
