### PR TITLE
MultiLineSelect doesn't need to move cursor

### PR DESCRIPTION
**Pull request by dzhou121**
## Summary
The current Gesture of MultiLineSelect has a bug that the cursor can't go to a position above the starting selection cursor position.  

Also, when you do a line selection, the cursor doesn't need to move to the end of the selection. 

## Review Checklist

- [ ] I have responded to reviews and made changes where appropriate.
- [x] I have tested the code with `cargo test --all` / `./rust/run_all_checks`.
- [ ] I have updated comments / documentation related to the changes I made.
- [x] I have rebased my PR branch onto xi-editor/master.

### CODE REVIEW

**Comment by cmyr** [comment]
@ryanbloom you've been in this code a bit lately, want to take a look?

**Comment by ryanbloom** [comment]
@dzhou121 I see there's something funny going on with `MultiLineSelect` on master, but it also seems to be happening on this branch. Could you describe how the behavior is supposed to be different?

(I'm using the xi-mac frontend, in case that has something to do with it.)

**Comment by ryanbloom** [comment]
Huh, that sounds pretty similar to how xi-mac does it. Here's the bug that I'm seeing (here and on master):

lineselect bug

The mouse is dragged to the top of the selection, but the cursor stays at the bottom. Does this branch fix the problem for your frontend?

I took a look at your code, and the main difference seems to be that `scroll_to_cursor` isn't called after the selection changes. I don't *think* that should affect where the cursor actually ends up. Maybe the different behavior we're getting has to do with how frontends handle scroll events?

**Comment by dzhou121** [comment]
I think this PR doesn't fix the bug for xi-mac, because if ```scroll_to_cursor``` isn't called, the cursor is left at the end of the selection. If ```scroll_to_cursor``` is called, there will be a explicit ```scroll_to``` which points the cursor to the end of selection. 

It fixed my front-end is because my front-end is emulating vim, so the ```scroll_to``` forces my cursor back to the end of the selection.

To fix the bug for xi-mac, I think we'll need to call ```scroll_to_cursor``` to the offset of the ```drag_to```

**Comment by cmyr** [comment]
@dzhou121 I'm still a little confused. I  think the best option here is to add some tests to `event_context.rs` that demonstrate the expected behaviour?

**Comment by cmyr** [comment]
@dzhou121 hi! Not sure if you're still interested in this patch, but if you can include a test case to show the behaviour you expect I would be happy to merge.

**Comment by dzhou121** [comment]
I think I was confused about the position of the cursor and the ```scroll_to``` event. So the actual cursor is in the ```update``` event, but in my frontend I'm using the ```scroll_to``` for the cursor position. So in this PR, it changes the behaviour of ```scroll_to``` event not to point to the end of the selection, but to point to the position in the incoming ```gesture``` or ```drag```.

**Comment by cmyr** [comment]
So this is all really on me, I never fully got my head around this PR. @dzhou121 if you're still interested in this I'd be happy to try again, otherwise I'm going to close. Sorry!

**Pull request closed without merging**
