### PR TITLE
[RFC] Session restoration

### PR DESCRIPTION
**Pull request by akxcv**
This is the first draft for the design of session restoration (#913).

### [Rendered](https://github.com/akxcv/xi-editor/blob/rfc/session-restoration/rfcs/session-restoration.md)

### CODE REVIEW

**Comment by cmyr** [comment]
broadly seems good, some very quick notes:

- it might be worth separating buffer info from view info; we will at some point support multiple views per buffer.

- json is reasonable at first, but we might want to consider [bincode](https://github.com/TyOverby/bincode); I'm not sure if this is already a dependency of ours (we might bring it in for theme caching?) but if it is then it might make sense to start there

- we might not want to write out the whole file each time there's a small update; we could have some approach where we write out changes as a log, and then periodically compact the log? We want to think about how to minimize the amount we're writing.

**Comment by cmyr** [comment]
yea, that's more or less my thinking, but obviously I haven't done any measuring or anything, so it's just gut feeling. It might be worth implementing this with like a `StateSerializer` trait where we can easily swap in different implementations?

**Comment by jansol** [comment]
If atomic saves rely on backup files e.g. like in vim, maybe store deltas at first against the original file, but after a certain amount of time (or # of edits) flush them to the backup and start storing deltas against that?

**Comment by jansol** [comment]
If atomic saves rely on backup files e.g. like in vim, maybe store deltas at first against the original file, but after a certain amount of time (or # of edits) flush them to the backup and start storing deltas against that?

**Comment by jansol** [comment]
Any news on this?

**Comment by akxcv** [comment]
> Any news on this?

I've been vacationing, and now I'm about to start working on this again.

**Comment by cmyr** [comment]
this particular attempt at this feature is on hold, and another attempt will provide its own design.

**Pull request closed without merging**
