### PR TITLE
Add benchmarks for rope editing operations.

### PR DESCRIPTION
**Pull request by vlovich**
This is an initial stab to add benchmarks for anyone wanting to tackle #583.

### CODE REVIEW

**Comment by vlovich** [comment]
Not yet ready for submitting so please don't merge.  Just here for feedback.

**Comment by cmyr** [comment]
Is there anything in particular you're looking for here? In any case @raphlinus would have the best idea of what might make for interesting benchmarks.

**Comment by cmyr** [comment]
@vlovich do you have any thoughts on this? taking a skim I think it would be reasonable to clean it up and merge, it certainly doesn't hurt to have more benchmarks written.

**Comment by mqzry** [comment]
He mentioned this in https://github.com/xi-editor/xi-editor/issues/583.
Apparently this PR is on my plate. Will look into it

**Comment by cmyr** [comment]
okay, let's close in favour of #828

**Pull request closed without merging**
