### PR TITLE
🚨Fix non-zero exit status of `run_all_checks` caused by linter errors

### LINKED ISSUE #1036: run_all_checks failing on master
# Xi-Editor Issue Template
- [x] I have searched existing issues and could not find my issue.
- [x] I have studied the documentation.

## Expected vs Actual

Expected `xi-editor/rust/run_all_checks` to exit with `0` status.

Actual: errors via `rustfmt` and `clippy` prevent test suite from running (unit test pass with `cargo test --all`)
```diff
$ xi-editor/rust/run_all_checks
      clippy 0.0.212 (29bf75cd 2018-12-05)
rustfmt 1.0.0-nightly (43206f41 2018-11-30)
Running rustfmt:
Diff in /Users/hartleymelamed/src/github.com/tzvipm/xi-editor/rust/core-lib/src/rpc.rs at line 568:
             Some(_) => {
                 return Err(de::Error::custom(
                     "'params' field, if present, must be object or array.",
-                ))
+                ));
             }
             None => false,
         };

Rustfmt failed. Please run rustfmt.
```

### PR DESCRIPTION
**Pull request by tzvipm**
## Summary
Fixes non-zero exit status of `run_all_checks` caused by linter errors.

## Related Issues
Closes #1036.

## Review Checklist
- [x] I have responded to reviews and made changes where appropriate.
- [x] I have tested the code with `cargo test --all` / `./rust/run_all_checks`.
- [x] I have updated comments / documentation related to the changes I made.
- [x] I have rebased my PR branch onto xi-editor/master.

### CODE REVIEW

**Comment by cmyr** [comment]
Oddly I'm not able to reproduce the failure, although your fixes look right. I wonder if we're using different versions of rustfmt? `rustfmt --version` for me prints `rustfmt 1.0.0-stable (4a4e5081 2018-11-29)`; `cargo clippy -- --version` prints `clippy 0.0.212 (2e26fdc2 2018-11-22)`; I believe these are current as of 1.31.

**Comment by jansol** [comment]
I'm inclined to close this due to lack of reproducibility, and because I believe that `rustfmt_skip` is generally not a solution.

**Comment by tzvipm** [comment]
Sorry, @jansol; I closed the issue, but seems I left the PR open.

**Comment by jansol** [comment]
Thanks, I didn't remember to check the issue.

**Pull request closed without merging**
