### PR TITLE
mark xi-mac as ready for daily use

### PR DESCRIPTION
**Pull request by matkoniecz**
## Summary

this is an attempt to make readme useful for people looking for an editor (uninterested in developing a new editor but the may be still useful as bug reporters)
based on comments in https://github.com/xi-editor/xi-editor/pull/1073
note that maybe also some other editors are also ready for daily use - let me know and I will update this PR

## Related Issues
* Related to #816 
* Replaces #1073

## Checklist

not applicable

## Review Checklist

- [x] I have responded to reviews and made changes where appropriate (not yet applicabble).
- [x] I have tested the code with `cargo test --all` / `./rust/run_all_checks` (not applicable).
- [x] I have updated comments / documentation related to the changes I made (not applicable).
- [x] I have rebased my PR branch onto xi-editor/master (not yet applicable).

### CODE REVIEW

**Comment by jansol** [comment]
I still don't really like the wording "ready for daily use" because it's varies so much by person. Instead I was thinking of something along the lines of a small feature matrix. The question is, what should be included there and what not?

**Comment by cmyr** [comment]
Yea, saying "ready" does scare me. while I might use xi-mac quite a bit myself, I definitely wouldn't make any stability guarantees.

I'm not sure what the real answer is, here.

**Comment by matkoniecz** [comment]
maybe "may be ready for daily use" or "some are using as their editor" or "ready for daily use, but keep in mind that it is in early development"?

Feature matrix that is not automatically generated is going to be obnoxious in maintenance and will be quickly outdated.

**Comment by z2oh** [comment]
I'm a rust fan and editor nerd, and I've been checking in on this project every now and then. I haven't bothered installing xi and using it yet because I assumed it was far from being stable as an actual editor. If xi is really ramping up to be useful as an editor, then you should let people know! As an outsider who has never used xi, seeing a feature matrix would be really awesome.

As @matkoniecz said, it would certainly become outdated quickly, but I would rather have an outdated guarantee about some minimal subset of functionality than no information at all!

**Comment by jansol** [comment]
@z2oh how did you conclude that it's not stable? I'm guessing the lack of prebuilt binaries.

That said, another preview build could be nice. The editing functionality itself is pretty much there IMHO, so (carefully) showing it off could be a good idea. But for an actual 1.0 release I'd personally want to have a solid enough plugin story that we can have some actual useful support for RLS and a better answer to multi-file projects than "just open 10 separate windows/tabs".

**Comment by z2oh** [comment]
@jansol The "Current status" section in the readme states:

> This is still a project in its early stages. The Mac build has basic editing functionality (it was used to write this README), but looks very spare and is still missing essentials such as auto-indent. At the moment, it’s expected that its main community will be developers interested in hacking on a text editor.

Judging from this PR, I'm not sure if the above statement is still completely accurate! I agree that a 1.0 release should be reserved for when the editor is truly ready, as you said, but a preview release would be awesome! It would make it much easier for interested parties to give a very exciting project a test run.

**Comment by cmyr** [comment]
A preview release would be nice, but I would not be comfortable with that at this stage; we are still moving quickly, and I still encounter crashing bugs. I do not want to offer anyone a 'product' until I am confident that we are _very_ unlikely to lose their data.

**Comment by cmyr** [comment]
So all this said: I'm going to close this issue, although I appreciate @matkoniecz's concerns, and I appreciate working to try and clarify things; I just don't currently think clarification is that helpful. I am not very satisfied by my answer, here, but I just don't see a nice clean answer. Sorry!

**Comment by z2oh** [comment]
@cmyr Fair enough!

When you do feel comfortable with a preview release _please_ do it! I look forward to the success of this project :)

**Pull request closed without merging**
