### PR TITLE
Apply clippy renames

### PR DESCRIPTION
**Pull request by Cogitri**
This fixes building with `cargo clippy -- -D warning`

### CODE REVIEW

**Comment by cmyr** [comment]
Were you running this against 1.31? It's certainly reasonable for us to bump rustc, but I suspect this is why CI is failing.

**Comment by Cogitri** [comment]
I think the CI failure is unrelated to this? Anyway, I tested against Rust 1.34 (CI) and 1.35 (beta. Only thing available for my platform (x86_64-unknown-linux-musl) right now).

**Comment by cmyr** [comment]
Yea, CI runs against Rust 1.31, currently. We keep ourselves pinned a few versions behind stable, although this isn't a firm rule (It was more important when we were regularly keeping fuchsia up to date, but that isn't the case at the moment and fuchsia is still on nightly anyway, afaik)

**Comment by Cogitri** [comment]
Hey @cmyr could you maybe look at the clippy failures? Clippy isn't yet available for my platform (it will be with the 1.35 release though, which should land soon-ish)

**Comment by cmyr** [comment]
The only failure seems to be this:

```
  --> rpc/src/test_utils.rs:70:60
   |
70 |         let resp = raw.map_err(|e| e.to_string()).and_then(|r| r.into_response());
   |                                                            ^^^^^^^^^^^^^^^^^^^^^ help: remove closure as shown: `parse::RpcObject::into_response`
   |
```

Want to try that suggestion and see if that gets us passing?

**Comment by Cogitri** [comment]
Sure, but I think it stops once it encounters a file with errors.

**Comment by Cogitri** [comment]
This works on my machine now.

**Comment by cmyr** [comment]
@Cogitri would you like to update this as per the zulip discission?

**Comment by Cogitri** [comment]
Ah, right, will do

**Comment by Cogitri** [comment]
Let's just use stable for now and (maybe) add 1.35.0 after 1.36.0 has been released

**Pull request merged**
