### PR TITLE
Update package versions for publishing

### PR DESCRIPTION
**Pull request by cmyr**
## Review Checklist

- [ ] I have responded to reviews and made changes where appropriate.
- [ ] I have tested the code with `cargo test --all` / `./rust/run_all_checks`.
- [ ] I have updated comments / documentation related to the changes I made.
- [ ] I have rebased my PR branch onto xi-editor/master.

### CODE REVIEW

**Comment by Cogitri** [comment]
What about the crates in the xi workspace you haven't touched (like trace/rope)?

**Comment by cmyr** [comment]
rope is already at 0.3 but hasn't been published. Trace is a funnier situation: it was only published at all for the first time recently. I think you're right that recent changes are breaking though, and it should get a bump.

**Comment by cmyr** [comment]
@Cogitri take a look when you get a chance?

**Comment by Cogitri** [comment]
Ah, lgtm, I'd only like to squeeze in #1190 before this :)

**Comment by cmyr** [comment]
Okay, going to get this in but will hold off on the actual release until we repin rustc.

**Pull request merged**
