### PR TITLE
Add Windows CI

### PR DESCRIPTION
**Pull request by jansol**
## Summary
Enables windows builds in Travis now that they support it, since we apparently don't have CI for windows yet. Not sure if that's wanted (are we moving to Cirrus or something?) so feel free to close this if not.

## Review Checklist

- [ ] I have responded to reviews and made changes where appropriate.
- [ ] I have tested the code with `cargo test --all` / `./rust/run_all_checks`.
- [x] I have updated comments / documentation related to the changes I made.
- [x] I have rebased my PR branch onto xi-editor/master.

### CODE REVIEW

**Comment by jansol** [comment]
Ah right, someone actually talked about that on #rust just today. I'm guessing this'll become a lot easier in the near(ish) future but I'll try hacking something together for now.

**Comment by jansol** [comment]
🎉 

Wow those builds take forever though, seems like cirrus is faster?

**Comment by LiHRaM** [comment]
Yeah, Cirrus uses some caching mechanism

**Comment by cmyr** [comment]
Is this done?

**Comment by jansol** [comment]
As you can see in the build's details, yes. (the PR already uses the updated travis.yml)

**Comment by cmyr** [comment]
I was more curious about whether you were also hoping to get Cirrus working in this PR. In any case travis is good!

**Pull request merged**
