### PR TITLE
Run cargo update

### PR DESCRIPTION
**Pull request by cmyr**
## Review Checklist

- [ ] I have responded to reviews and made changes where appropriate.
- [ ] I have tested the code with `cargo test --all` / `./rust/run_all_checks`.
- [ ] I have updated comments / documentation related to the changes I made.
- [ ] I have rebased my PR branch onto xi-editor/master.

### CODE REVIEW

**Comment by Cogitri** [comment]
I think you might want to re-run `cargo update`, a few bits have become out-of-date again (like serde) :)

**Comment by Cogitri** [comment]
Could you also bump `dirs` then?

**Comment by Cogitri** [comment]
Nevermind, just saw your new commit. Thanks!

**Comment by Cogitri** [comment]
Related, could we switch over `xi-syntect-plugin` 3.0.4 of syntect instead of using git?

**Comment by cmyr** [comment]
why 3.0.4? (I see that 3.2 exists?)

**Comment by Cogitri** [comment]
Oops, remembered wrong number, meant 3.2.0 ^^

**Pull request merged**
